FROM amazon/aws-cli
RUN amazon-linux-extras install docker
RUN yum install jq -y

FROM amazon/aws-cli:latest

USER root

RUN yum update -y \
 && yum install -y \
      docker \
      jq \
 && yum clean all

ENTRYPOINT ["aws"]
CMD ["--help"]
